### ISSUE TITLE
missing Trace

### ISSUE THREAD

**Issue by codemeasandwich** [codemeasandwich/scribbles#27]
https://www.geeksforgeeks.org/node-js-console-trace-method/

**Comment by codemeasandwich** [comment]
What if trace also give the same source view as jest ?
```
      191 |   }catch(err){
      192 |   
    > 193 |        scribbles.trace(foo)
      194 |
      195 |    }

      at catch (code/app.ts:13:19)
      at main (code/app.ts:63:10)
      at  main (code/app.ts:31:12)
```

2 lines before & 2 lines after
