### ISSUE TITLE
Error in setting scribbles as global.console

### ISSUE THREAD

**Issue by codemeasandwich** [codemeasandwich/scribbles#9]
function args2keys(args, notUsed){
                  ^
RangeError: Maximum call stack size exceeded
    at args2keys (/code/sample/node_modules/scribbles/src/args2keys.js:1:19)
    at scribble (/code/sample/node_modules/scribbles/index.js:110:37)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)
    at scribble (/code/sample/node_modules/scribbles/index.js:142:9)

https://github.com/codemeasandwich/scribbles/blob/80c4dcd93ae6f9f515edbbeccf76676e6cea7c38/index.js#L142

**Comment by codemeasandwich** [comment]
754de54882b9896c93bc4277ec42dcedf5365ef0
